[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ask-my-shipment"
version = "0.1.0"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["utils"]